In [1]:
import networkx as nx
import pandas as pd
import json
from sklearn.model_selection import train_test_split

In [2]:
targetDE=pd.read_csv("./twitch/DE/musae_DE_target.csv")

In [3]:
targetDE

             id  days  mature     views  partner  new_id
0      37905227  2149    True    162078    False    5079
1      63102384  1574    True      1370    False    4281
2     109414094  1034    True      6043    False     992
3      84163849  1319    True     94298     True    9021
4      38240837  2137    True      2323    False     330
...         ...   ...     ...       ...      ...     ...
9493  123101102   895    True       128    False    4572
9494   40627165  2001   False        44    False    6355
9495   50643307  1784    True      2038    False     206
9496   38810779  2114   False       449    False    7695
9497   58351323  1680   False  10638954     True    4451

[9498 rows x 6 columns]

In [4]:
edgesDE=pd.read_csv("./twitch/DE/musae_DE_edges.csv")

In [5]:
target=pd.read_csv("./twitch/FR/musae_FR_target.csv")

In [6]:
edges=pd.read_csv("./twitch/FR/musae_FR_edges.csv")

In [7]:
edgesDE

        from    to
0          0  9206
1          0  7787
2          0  2145
3          0  2684
4          0  7275
...      ...   ...
153133  2547  2092
153134  9461  2092
153135  9295  7802
153136  7436  9487
153137  1793  9194

[153138 rows x 2 columns]

In [8]:
target["mature"].value_counts()

False    4135
True     2416
Name: mature, dtype: int64

In [9]:
target

             id  days  mature  views  partner  new_id
0     150417538   577    True    775    False    4867
1     125723704   861    True   2585    False    3692
2     155971814   523   False   1566    False    3816
3      35832890  2234   False   9713    False     416
4      46787750  1896    True  44529    False    4502
...         ...   ...     ...    ...      ...     ...
6546   29196284  2061   False   3822    False    6546
6547  124327806   880    True  30313    False    2392
6548  144229380   640    True   5022    False     391
6549  131423064   736   False   2658    False    2793
6550   45419243  1929    True   3743    False    1092

[6551 rows x 6 columns]

In [10]:
graph_path="./twitch/FR/musae_FR_features.json"

In [11]:
graph_path_DE="./twitch/DE/musae_DE.json"

In [12]:

# load JSON data from file
with open(graph_path, 'r') as f:
    data = json.load(f)

# create new NetworkX graph
G = nx.Graph()

In [13]:

# load JSON data from file
with open(graph_path_DE, 'r') as f:
    dataDE = json.load(f)

# create new NetworkX graph
G_DE = nx.Graph()

In [14]:
G = nx.from_dict_of_lists(data)

# visualize the graph
#nx.draw(G, with_labels=True)

In [15]:
G_DE = nx.from_dict_of_lists(dataDE)

# visualize the graph
#nx.draw(G, with_labels=True)

In [16]:
mat=nx.adjacency_matrix(G).toarray()

In [17]:
mat_DE=nx.adjacency_matrix(G_DE).toarray()

In [18]:
mat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [19]:
target

             id  days  mature  views  partner  new_id
0     150417538   577    True    775    False    4867
1     125723704   861    True   2585    False    3692
2     155971814   523   False   1566    False    3816
3      35832890  2234   False   9713    False     416
4      46787750  1896    True  44529    False    4502
...         ...   ...     ...    ...      ...     ...
6546   29196284  2061   False   3822    False    6546
6547  124327806   880    True  30313    False    2392
6548  144229380   640    True   5022    False     391
6549  131423064   736   False   2658    False    2793
6550   45419243  1929    True   3743    False    1092

[6551 rows x 6 columns]

In [20]:
#Algorithme 1

In [21]:
def binary(x):
    if x==True:
        return 1
    else:
        return -1

In [22]:
target["mature"]=target["mature"].apply(binary)

In [23]:
target["partner"]=target["partner"].apply(binary)

In [24]:
unlabeled,labeled=train_test_split(target,test_size=0.8)

In [25]:
labeled

             id  days  mature   views  partner  new_id
530   161969958   470      -1   11137       -1    5584
1788   38309435  2132       1   33531       -1    1433
4949   97270264  1169      -1    6360       -1    5882
6514   80736066  1356      -1    2764       -1    4734
3667   24993964  2577       1   44677       -1    3338
...         ...   ...     ...     ...      ...     ...
4176   62128391  1622       1   79023       -1      88
2995  116686593   962      -1  525188        1    6427
5337   53517301  1758      -1   32040       -1    4037
4849   52295414  1778      -1     774       -1    5562
2532  111389683  1014       1   10383       -1    4436

[5241 rows x 6 columns]

In [26]:
unlabeled

             id  days  mature    views  partner  new_id
3839  120635447   924       1     8120       -1      15
3395   25437945  2555       1    19946       -1    3966
2057  116077926   965       1     2315       -1    5405
4918   68331236  1487      -1      260       -1    3956
1667   38126275  2141      -1    15798       -1     262
...         ...   ...     ...      ...      ...     ...
4059   55409729  1724      -1    51905       -1    6036
3617  132802067   772      -1     1391       -1    3876
5341   51074510  1804      -1    15781       -1    2220
2572   55411549  1533      -1       16       -1     328
3593    4102418  3530      -1  5760863        1    2560

[1310 rows x 6 columns]

In [27]:
import numpy as np

def label_propagation(G, Yl, max_iter=100, tol=1e-4):
    """
    Label propagation algorithm for graph G with initial labels Yl.

    Parameters:
    - G: numpy array, adjacency matrix of the graph.
    - Yl: numpy array, initial labels for some of the nodes.
    - max_iter: int, maximum number of iterations.
    - tol: float, convergence threshold.

    Returns:
    - Y: numpy array, final labels for all nodes.
    """
    D = np.diagflat(np.sum(G, axis=1)[0:,])
    

    # Compute the transition matrix.
    P = np.linalg.inv(D) @ G

    # Initialize the label vector.
    Y = np.zeros(G.shape[0])
    Y[Yl[:, 0]] = Yl[:, 1]

    # Iterate until convergence.
    for i in range(max_iter):
        Y_new = P @ Y
        Y_new[Yl[:, 0]] = Y[Yl[:, 0]]
        if np.linalg.norm(Y_new - Y) < tol:
            break
        Y = Y_new

    return Y

In [28]:
Yl=[]
for _,row in labeled.iterrows():
    Yl.append([row["new_id"],row["mature"]])

In [29]:
Yl_unlab=[]
for _,row in unlabeled.iterrows():
    Yl_unlab.append([row["new_id"],row["mature"]])

In [30]:
Yl=np.array(Yl)

In [31]:
Yl_unlab=np.array(Yl_unlab)

In [32]:
Y=label_propagation(mat,Yl)

In [33]:
correct=0
negpred=0
pospred=0
for i in range(0,Yl_unlab.shape[0]):
    ind=Yl_unlab[i,0]
    truelabel=Yl_unlab[i,1]
    if Y[ind]>=0 and  truelabel>=0:
        correct+=1
        pospred+=1
    if Y[ind]<=0 and  truelabel<=0:
        correct+=1
        negpred+=1

In [34]:
correct/Yl_unlab.shape[0]

0.6465648854961832

In [35]:
negpred

847

In [36]:
pospred

0

In [37]:
np.diagflat(np.sum(mat, axis=1)[0:,])

array([[11,  0,  0, ...,  0,  0,  0],
       [ 0, 29,  0, ...,  0,  0,  0],
       [ 0,  0, 21, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  1,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0,  0,  1]], dtype=int32)

In [38]:
max_iter=10000

In [39]:
tol=1e-4

In [40]:
mat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [41]:
G=mat

In [42]:
D = np.diagflat(np.sum(mat, axis=1)[0:,])
print(D)

# Compute the transition matrix.
P = np.linalg.inv(D) @ mat

# Initialize the label vector.
Y = np.zeros(mat.shape[0])
Y[Yl[:, 0]] = Yl[:, 1]

# Iterate until convergence.
for i in range(max_iter):
    Y_new = P @ Y
    Y_new[Yl[:, 0]] = Y[Yl[:, 0]]
    if np.linalg.norm(Y_new - Y) < tol:
        break
    Y = Y_new

[[11  0  0 ...  0  0  0]
 [ 0 29  0 ...  0  0  0]
 [ 0  0 21 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]]

In [43]:
import numpy as np
from sklearn.base import clone

def iterative_classification(G, Yl, clf, max_iter=100, tol=1e-4):
    """
    Iterative classification algorithm for graph G with initial labels Yl.

    Parameters:
    - G: numpy array, adjacency matrix of the graph.
    - Yl: numpy array, initial labels for some of the nodes.
    - clf: scikit-learn classifier object, classifier to use for classification.
    - max_iter: int, maximum number of iterations.
    - tol: float, convergence threshold.

    Returns:
    - Y: numpy array, final labels for all nodes.
    """
    D = np.diagflat(np.sum(G, axis=1)[0:,])
    
    # Compute the transition matrix.
    P = np.linalg.inv(D) @ G

    # Initialize the label vector.
    Y = np.zeros(G.shape[0])
    Y[Yl[:, 0]] = Yl[:, 1]

    # Initialize feature matrix.
    X = np.zeros((G.shape[0], clf.n_features_))
    X[Yl[:, 0]] = clf.transform(G[Yl[:, 0], :])

    # Iterate until convergence.
    for i in range(max_iter):
        # Train classifier on labeled nodes.
        clf.fit(X[Yl[:, 0]], Y[Yl[:, 0]])
        
        # Predict labels for unlabeled nodes.
        Y_new = clf.predict(X[Vu, :])
        
        # Update labeled nodes.
        Y[Yl[:, 0]] = Yl[:, 1]
        X[Yl[:, 0]] = clf.transform(G[Yl[:, 0], :])
        
        # Check for convergence.
        if np.linalg.norm(Y_new - Y[Vu]) < tol:
            break
        
        # Add new labeled nodes.
        new_labeled = np.vstack((Vu[Y_new != Y[Vu]], Y_new[Y_new != Y[Vu]])).T
        Yl = np.vstack((Yl, new_labeled))
        
        # Update feature matrix.
        X[new_labeled[:, 0]] = clf.transform(G[new_labeled[:, 0], :])
        
        # Update labeled and unlabeled node sets.
        Vl = np.unique(Yl[:, 0])
        Vu = np.setdiff1d(range(G.shape[0]), Vl)
    
    return Y

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X, y)

print(clf.predict([[0, 0, 0, 0]]))

[1]

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV

X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)

param_grid = {
    'max_depth': [2, 4, 6, 8],
    'n_estimators': [50, 100, 200, 400]
}

clf = RandomForestClassifier(random_state=0)

grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, n_jobs=-1)
grid_search.fit(X, y)

print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

Best hyperparameters: {'max_depth': 6, 'n_estimators': 100}
Best score: 0.9490000000000001

In [46]:
X

array([[-1.66853167, -1.29901346,  0.2746472 , -0.60362044],
       [-2.9728827 , -1.08878294,  0.70885958,  0.42281857],
       [-0.59614125, -1.37007001, -3.11685659,  0.64445203],
       ...,
       [ 0.91711204,  1.10596645,  0.86766522, -2.25625012],
       [ 0.10027664,  1.45875846, -0.44360274, -0.67002328],
       [ 1.0415229 , -0.01987143,  0.15216419, -1.9405334 ]])

In [47]:
X.shape

(1000, 4)

In [48]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [49]:
y.shape

(1000,)

In [50]:
labeled[["mature"]].value_counts()

mature
-1        3288
 1        1953
dtype: int64

In [51]:
unlabeled[["mature"]].value_counts()

mature
-1        847
 1        463
dtype: int64

In [52]:
label_to_predict=labeled["mature"]

In [53]:
label_to_test=unlabeled["mature"]

In [54]:
train=labeled.drop("mature",axis=1)

In [55]:
test=unlabeled.drop("mature",axis=1)

In [56]:
clf.fit(train,label_to_predict)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV


param_grid = {
    'max_depth': [2, 4, 6, 8],
    'n_estimators': [50, 100, 200, 400]
}

clf = RandomForestClassifier(random_state=0)

grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, n_jobs=-1)
grid_search.fit(train, label_to_predict)

print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

Best hyperparameters: {'max_depth': 6, 'n_estimators': 200}
Best score: 0.631179458444611

In [58]:
pred=clf.predict(test)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(label_to_test, pred)

In [60]:
with open('../facebook/1684.edges', 'r') as f:
    edges = [tuple(map(int, line.strip().split())) for line in f]

In [61]:
edges

[(2849, 3021),
 (2694, 3096),
 (2818, 2725),
 (2951, 3285),
 (3082, 2832),
 (2960, 2800),
 (2929, 3029),
 (2909, 2880),
 (2754, 2872),
 (3232, 2880),
 (3184, 2948),
 (3277, 3297),
 (3096, 2925),
 (3397, 2939),
 (3185, 3115),
 (2927, 3426),
 (3333, 3394),
 (3087, 3236),
 (3327, 2675),
 (2863, 3296),
 (3293, 3384),
 (3005, 3039),
 (3428, 3139),
 (3198, 3082),
 (3184, 3417),
 (2944, 2738),
 (3399, 2777),
 (2894, 3320),
 (2793, 2787),
 (3377, 2778),
 (3101, 3214),
 (3090, 2729),
 (3085, 2966),
 (3033, 2919),
 (2893, 2771),
 (2749, 2986),
 (2829, 2711),
 (2755, 3149),
 (3029, 2887),
 (3247, 3347),
 (3065, 2986),
 (3286, 3417),
 (3021, 3419),
 (3319, 3046),
 (2773, 2666),
 (2706, 2927),
 (2940, 2852),
 (2944, 3226),
 (2939, 3316),
 (3050, 2667),
 (3117, 3173),
 (2913, 2676),
 (2872, 3033),
 (2878, 3249),
 (2897, 3119),
 (3204, 3351),
 (2801, 3256),
 (3191, 3203),
 (2863, 3204),
 (2846, 3321),
 (3417, 2755),
 (3124, 2803),
 (3280, 3132),
 (3207, 2951),
 (2754, 2966),
 (3042, 2963),
 (3090, 2987),
 (2946, 3335),
 (2697, 3292),
 (3026, 2786),
 (3170, 2875),
 (2927, 3047),
 (3108, 2750),
 (3108, 2908),
 (3191, 3412),
 (3056, 2927),
 (3029, 3025),
 (2754, 2940),
 (3426, 3026),
 (2679, 2756),
 (3098, 2906),
 (3247, 3120),
 (2916, 2680),
 (2742, 3350),
 (2716, 3051),
 (3240, 3051),
 (3331, 1405),
 (3090, 2905),
 (3051, 3145),
 (3045, 2789),
 (3182, 3434),
 (3420, 2730),
 (3106, 3397),
 (3307, 2847),
 (3396, 3280),
 (2936, 3198),
 (3361, 2764),
 (3293, 2754),
 (3018, 3248),
 (2856, 3115),
 (3156, 2843),
 (2945, 3257),
 (3263, 3057),
 (2888, 2738),
 (3287, 2840),
 (2731, 2821),
 (2985, 2750),
 (2946, 2698),
 (3360, 2989),
 (2683, 3301),
 (2907, 2928),
 (3385, 2795),
 (3239, 2661),
 (2910, 2909),
 (3233, 3244),
 (2756, 2929),
 (3391, 3049),
 (3392, 3090),
 (3193, 2706),
 (3096, 3054),
 (2690, 2787),
 (2844, 3087),
 (3252, 3355),
 (2718, 3136),
 (2742, 3152),
 (3366, 3346),
 (2904, 2716),
 (3150, 3102),
 (3419, 3169),
 (3173, 3117),
 (2905, 3384),
 (3178, 3208),
 (3267, 3101),
 (3116, 2894),
 (3386, 2665),
 (3182, 3332),
 (3243, 2679),
 (2886, 2999),
 (2708, 3145),
 (3252, 3016),
 (2698, 3096),
 (2936, 3082),
 (3342, 3106),
 (3022, 2698),
 (3306, 3298),
 (3411, 3208),
 (2793, 2833),
 (2887, 2994),
 (3106, 3416),
 (3296, 2863),
 (3064, 2689),
 (3104, 3364),
 (3204, 3302),
 (3291, 2783),
 (2818, 2734),
 (3320, 2828),
 (3353, 3035),
 (3043, 2871),
 (2739, 3233),
 (3193, 3324),
 (3339, 2694),
 (3345, 3299),
 (2913, 3104),
 (3090, 2757),
 (3288, 3182),
 (3391, 3434),
 (3226, 2925),
 (3026, 3234),
 (2992, 2716),
 (3335, 3116),
 (2854, 3234),
 (3018, 2724),
 (3425, 3402),
 (2909, 2920),
 (3095, 2877),
 (3051, 3060),
 (3054, 2782),
 (3350, 3355),
 (3000, 3174),
 (3094, 2765),
 (2869, 2991),
 (3385, 3198),
 (3078, 2920),
 (2940, 2717),
 (3225, 3024),
 (3064, 3232),
 (2888, 3231),
 (3280, 3035),
 (2849, 3335),
 (2919, 2943),
 (3009, 2901),
 (3107, 3343),
 (3253, 3087),
 (2832, 3214),
 (3086, 2688),
 (3068, 3415),
 (3321, 3406),
 (2794, 3073),
 (3374, 2964),
 (2992, 2936),
 (3145, 2992),
 (2715, 2865),
 (2778, 2661),
 (2748, 3215),
 (2901, 3051),
 (2978, 3430),
 (2985, 2755),
 (3077, 2968),
 (3256, 3167),
 (3040, 2994),
 (3040, 2676),
 (3385, 2918),
 (3394, 2890),
 (3415, 2892),
 (3022, 2877),
 (3416, 3049),
 (3074, 3127),
 (3289, 2955),
 (2951, 2813),
 (3234, 3184),
 (2666, 2749),
 (2827, 3033),
 (3118, 2711),
 (3019, 3380),
 (2780, 3152),
 (3332, 3262),
 (3118, 2840),
 (2694, 3417),
 (2803, 2772),
 (3347, 3145),
 (3327, 3366),
 (2835, 2763),
 (2662, 3206),
 (2730, 2871),
 (3226, 2835),
 (3176, 3086),
 (2863, 3201),
 (3042, 3114),
 (3392, 2726),
 (2953, 2877),
 (3347, 3005),
 (3330, 3145),
 (2754, 3137),
 (3328, 3144),
 (3136, 3369),
 (3079, 3396),
 (3096, 2749),
 (2719, 3353),
 (3403, 3287),
 (3104, 2729),
 (3044, 2800),
 (3252, 3297),
 (3384, 2738),
 (3253, 2665),
 (3273, 2728),
 (2864, 3387),
 (2782, 2877),
 (2683, 3237),
 (3014, 3387),
 (3033, 3117),
 (3219, 3214),
 (3101, 3076),
 (2720, 3344),
 (3085, 3348),
 (2741, 2839),
 (3360, 3335),
 (2946, 3119),
 (2810, 3417),
 (3226, 2911),
 (3414, 2706),
 (3259, 3189),
 (3324, 2745),
 (2661, 2853),
 (3158, 3123),
 (3295, 3001),
 (3075, 2921),
 (3152, 2869),
 (2745, 3387),
 (3417, 3364),
 (2820, 3001),
 (2928, 2896),
 (2988, 2873),
 (2800, 2810),
 (3064, 2920),
 (3082, 3391),
 (2702, 2675),
 (2988, 3119),
 (3232, 2874),
 (3026, 3033),
 (3277, 3016),
 (2689, 3417),
 (3013, 2687),
 (3099, 3242),
 (3138, 3178),
 (3162, 3233),
 (2923, 2677),
 (2748, 3046),
 (2724, 3379),
 (3426, 2759),
 (3278, 1534),
 (2851, 3394),
 (2938, 3289),
 (3113, 3060),
 (3378, 3397),
 (2866, 3399),
 (3339, 3104),
 (2760, 2790),
 (2777, 2867),
 (2834, 3423),
 (2909, 2891),
 (2870, 3246),
 (2919, 2912),
 (3198, 2780),
 (2940, 3348),
 (2956, 3364),
 (2829, 3241),
 (3426, 2750),
 (2897, 3054),
 (3363, 2986),
 (3240, 3344),
 (3315, 2948),
 (2661, 3152),
 (2956, 2698),
 (2951, 3017),
 (3252, 3320),
 (3172, 3112),
 (3174, 2916),
 (3104, 2929),
 (3077, 2892),
 (3344, 2720),
 (3150, 2883),
 (2909, 3064),
 (2916, 2800),
 (2919, 2669),
 (3115, 3049),
 (2831, 3256),
 (3326, 2781),
 (3129, 2669),
 (2773, 3362),
 (2669, 2866),
 (2919, 2905),
 (3098, 2800),
 (2863, 3102),
 (2724, 3223),
 (2801, 2865),
 (2996, 3341),
 (2997, 2933),
 (3079, 3060),
 (2973, 3212),
 (2871, 2950),
 (3185, 3111),
 (1758, 2764),
 (2986, 2909),
 (3218, 3053),
 (3396, 3082),
 (2758, 2918),
 (3076, 2672),
 (2919, 2676),
 (2907, 2679),
 (3261, 3280),
 (2877, 2896),
 (3145, 3201),
 (3086, 3420),
 (3348, 2890),
 (3318, 2834),
 (3366, 3077),
 (2818, 2700),
 (1405, 3100),
 (3339, 2679),
 (2918, 3173),
 (3247, 2748),
 (3026, 2815),
 (3247, 3291),
 (3156, 3256),
 (3363, 2729),
 (3029, 3073),
 (3086, 3379),
 (2815, 2905),
 (2815, 3096),
 (3302, 3101),
 (3266, 3398),
 (2986, 3226),
 (3435, 3000),
 (2760, 3222),
 (2777, 3098),
 (2999, 2764),
 (2751, 3117),
 (2906, 3226),
 (2966, 2987),
 (3192, 3422),
 (2943, 2919),
 (2916, 3065),
 (3069, 3191),
 (3298, 2778),
 (3258, 2937),
 (2733, 3185),
 (3391, 2853),
 (2989, 3075),
 (3169, 3397),
 (3240, 3316),
 (2717, 2920),
 (2696, 2820),
 (3169, 3106),
 (2698, 2666),
 (2662, 2830),
 (2871, 3136),
 (2666, 3014),
 (3154, 2716),
 (2753, 2973),
 (3101, 2796),
 (2708, 3172),
 (2931, 3394),
 (3029, 2931),
 (3113, 3335),
 (2911, 2864),
 (3051, 2778),
 (3295, 2682),
 (3313, 3075),
 (3291, 3406),
 (3212, 2856),
 (3430, 3123),
 (3324, 3227),
 (3344, 2793),
 (2679, 2777),
 (2674, 3247),
 (2906, 2911),
 (3032, 2730),
 (3352, 3188),
 (3363, 2782),
 (3185, 3017),
 (3219, 3337),
 (3366, 3356),
 (1450, 2968),
 (2897, 2966),
 (3166, 2773),
 (2873, 2729),
 (3077, 3207),
 (3330, 2951),
 (3124, 3312),
 (3160, 3355),
 (3201, 1642),
 (3174, 2800),
 (3162, 3144),
 (2945, 2756),
 (3301, 2906),
 (3288, 3313),
 (2866, 2993),
 (2781, 3347),
 (2806, 3213),
 (2818, 2748),
 (2770, 3152),
 (3178, 2848),
 (3119, 3123),
 (2782, 3108),
 (3232, 2694),
 (2908, 3004),
 (3352, 2742),
 (3300, 3059),
 (2863, 3113),
 (2777, 2969),
 (3158, 2987),
 (3182, 3204),
 (2913, 2925),
 (3135, 2993),
 (2690, 3018),
 (2780, 3146),
 (2904, 2770),
 (2946, 2862),
 (3198, 3101),
 (2683, 2773),
 (2675, 3256),
 (3416, 3070),
 (3021, 3397),
 (3326, 3090),
 (2927, 2915),
 (3180, 2732),
 (3356, 3285),
 (3365, 2690),
 (2724, 3191),
 (3347, 3416),
 (2927, 3400),
 (3363, 2874),
 (2819, 3035),
 (2969, 3387),
 (2953, 3364),
 (3309, 2879),
 (3320, 3355),
 (3070, 2753),
 (2944, 2800),
 (3049, 2973),
 (3418, 3124),
 (3226, 3064),
 (3115, 3124),
 (2717, 2839),
 (2675, 2730),
 (2943, 2966),
 (3351, 3152),
 (3102, 3434),
 (2967, 3092),
 (3146, 3347),
 (2673, 3004),
 (3022, 3064),
 (2689, 2943),
 (2912, 2694),
 (2863, 2785),
 (3420, 3412),
 (3366, 3027),
 (3171, 2841),
 (3301, 2755),
 (3064, 2717),
 (3042, 2915),
 (2962, 2934),
 (2688, 3146),
 (2750, 2827),
 (3023, 2945),
 (2729, 3433),
 (2986, 3195),
 (2720, 3009),
 (2854, 2683),
 (3119, 3435),
 (2816, 3256),
 (2763, 3213),
 (3220, 2974),
 (2770, 3150),
 (3240, 3101),
 (2870, 3017),
 (2755, 3228),
 (3095, 3392),
 (2821, 2731),
 (2735, 2709),
 (3002, 3287),
 (3240, 2951),
 (2965, 3328),
 (2944, 2867),
 (2676, 3078),
 (3240, 3355),
 (3390, 2683),
 (2672, 3332),
 (2894, 3198),
 (3220, 2754),
 (2662, 2753),
 (3339, 2905),
 (2904, 3342),
 (3277, 2778),
 (3000, 2897),
 (2773, 3084),
 (1505, 3245),
 (3350, 3262),
 (3010, 3025),
 (2956, 2800),
 (2869, 1666),
 (3104, 3080),
 (2866, 3387),
 (3201, 2712),
 (2864, 3004),
 (2943, 3096),
 (1666, 1450),
 (2871, 3002),
 (2936, 3373),
 (2793, 3120),
 (2830, 2724),
 (2955, 3402),
 (3078, 2940),
 (2919, 2864),
 (3277, 2796),
 (2694, 3174),
 (3022, 3054),
 (2920, 2750),
 (3039, 2796),
 (3247, 2863),
 (3265, 3351),
 (3120, 3154),
 (3132, 3049),
 (3164, 3057),
 (3151, 3214),
 (2862, 2946),
 (2662, 3027),
 (3347, 2939),
 (3342, 3421),
 (3148, 3411),
 (3284, 2877),
 (3237, 2891),
 (3321, 2901),
 (3300, 3084),
 (2872, 2956),
 (2843, 2675),
 (2724, 3370),
 (3145, 3082),
 (2909, 2916),
 (3043, 3093),
 (2669, 3096),
 (3191, 2951),
 (3070, 3049),
 (3041, 2989),
 (2679, 2862),
 (2730, 3219),
 (3169, 2939),
 (3352, 2846),
 (3060, 3112),
 (2986, 2680),
 (3082, 3416),
 (3108, 2864),
 (2764, 3263),
 (107, 1726),
 (2905, 2773),
 (2681, 3433),
 (2754, 2746),
 (3348, 3384),
 (3142, 2912),
 (3146, 2828),
 (3008, 3318),
 (2786, 2943),
 (2958, 3331),
 (3403, 3148),
 (3419, 2863),
 (2967, 3213),
 (3130, 2851),
 (2711, 2667),
 (2892, 1405),
 (3195, 2694),
 (3158, 3433),
 (3393, 2831),
 (3120, 3297),
 (2991, 3082),
 (3049, 3201),
 (2873, 3000),
 (3320, 2707),
 (3417, 2839),
 (2915, 2943),
 (3084, 3130),
 (2862, 2915),
 (2778, 3267),
 (3193, 3023),
 (3406, 2716),
 (2920, 2852),
 (2729, 3036),
 (3394, 2854),
 (2741, 2910),
 (2828, 3132),
 (3272, 3351),
 (2932, 3255),
 (2662, 3154),
 (2850, 3193),
 (3181, 2732),
 (3039, 3076),
 (2687, 3321),
 (3096, 3056),
 (3179, 3434),
 (3014, 2912),
 (2757, 3098),
 (2880, 2946),
 (2904, 3298),
 (2755, 3014),
 (2909, 3052),
 (2974, 2669),
 (2921, 3034),
 (3025, 2887),
 (2940, 2706),
 (3277, 2996),
 (2778, 3120),
 (3078, 2698),
 (3150, 3411),
 (3397, 3261),
 (3075, 3323),
 (3321, 3116),
 (2854, 3213),
 (2863, 3274),
 (2793, 2661),
 (3085, 2839),
 (2913, 3195),
 (2866, 2916),
 (2877, 2680),
 (3264, 3196),
 (2757, 2916),
 (2915, 3064),
 (2666, 2956),
 (3154, 3321),
 (3243, 3433),
 (3120, 3191),
 (3181, 2930),
 (3297, 3288),
 (3094, 2939),
 (3011, 2968),
 (2896, 2786),
 (3135, 2689),
 (3392, 2978),
 (3097, 3177),
 (3043, 3369),
 (2955, 2941),
 (3102, 3185),
 (3027, 2992),
 (3346, 2830),
 (2991, 3204),
 (3160, 3397),
 (3364, 3029),
 (3171, 3136),
 (3036, 3394),
 (2967, 2664),
 (3149, 2755),
 (2735, 3244),
 (3137, 2731),
 (3146, 2674),
 (2763, 2806),
 (2855, 2904),
 (3419, 2781),
 (3072, 3287),
 (3214, 3002),
 (2992, 3320),
 (3228, 3117),
 (2959, 3325),
 (2770, 3277),
 (2742, 2712),
 (3060, 3330),
 (1666, 3258),
 (3254, 3280),
 (990, 3222),
 (2754, 2974),
 (3216, 3141),
 (3304, 2946),
 (3339, 3362),
 (2749, 2940),
 (3381, 3120),
 (3004, 2919),
 (3198, 3255),
 (2778, 3366),
 (2679, 2927),
 (3092, 3324),
 (2912, 3142),
 (2789, 2851),
 (2676, 2694),
 (2742, 3406),
 (3119, 2821),
 (2685, 2865),
 (3363, 3036),
 (3109, 2785),
 (2668, 3140),
 (2723, 2836),
 (2923, 3265),
 (2708, 3179),
 (3017, 3367),
 (3213, 2786),
 (2790, 2848),
 (2719, 3274),
 (3287, 2976),
 (3075, 2686),
 (3185, 3378),
 (2966, 2689),
 (2993, 3387),
 (3168, 3405),
 (2873, 2929),
 (3360, 2716),
 (2887, 3036),
 (2936, 3145),
 (3298, 3378),
 (3136, 3341),
 (3280, 3360),
 (2841, 2771),
 (2946, 3387),
 (3064, 3096),
 (2738, 2877),
 (3149, 2757),
 (2741, 2994),
 (2679, 3184),
 (2850, 2966),
 (3162, 2900),
 (2786, 3384),
 (3413, 2821),
 (2719, 2778),
 (2955, 3187),
 (3297, 3277),
 (3081, 3259),
 (3051, 3288),
 (2759, 3095),
 (2948, 3234),
 (3002, 3263),
 (3166, 2731),
 (3094, 3267),
 (2879, 3283),
 (2862, 2929),
 (3287, 3111),
 (2833, 3288),
 (3406, 2904),
 (2806, 2800),
 (3034, 2716),
 (2757, 2974),
 (2840, 3396),
 (2795, 2793),
 (2782, 2910),
 (3168, 2739),
 (2873, 3435),
 (3000, 3433),
 (2720, 2937),
 (2864, 2850),
 (3099, 3369),
 (3056, 3363),
 (3165, 3343),
 (3154, 3162),
 (3293, 3394),
 (2680, 3363),
 (3179, 3351),
 (2754, 3129),
 (3360, 3351),
 (3300, 3430),
 (2768, 3151),
 (2683, 3096),
 (2828, 2719),
 (2701, 3079),
 (3002, 2892),
 (2853, 3335),
 (3263, 3259),
 (3000, 2944),
 (3265, 3188),
 (3411, 2665),
 (3104, 2988),
 (3267, 3146),
 (3207, 3086),
 (3256, 2950),
 (3136, 2686),
 (2840, 2727),
 (3022, 2664),
 (2686, 2702),
 (3049, 3277),
 (2890, 3142),
 (3086, 3018),
 (3295, 3273),
 (3355, 3212),
 (3283, 2982),
 (2706, 2911),
 (2783, 3185),
 (2688, 2693),
 (3019, 2739),
 (3353, 2984),
 (3117, 3228),
 (2765, 2973),
 (2980, 3267),
 (2712, 2833),
 (2944, 3090),
 (3297, 2793),
 (3076, 3132),
 (2699, 2703),
 (1505, 3168),
 (3315, 3193),
 (2870, 3244),
 (3237, 2839),
 (2944, 3394),
 (3169, 3146),
 (3232, 3040),
 (3002, 3089),
 (3077, 3412),
 (2974, 3284),
 (2760, 2813),
 (2878, 2751),
 (2764, 3278),
 (2797, 2672),
 (2661, 3381),
 (3195, 2917),
 (2863, 3235),
 (2877, 2911),
 (3101, 3224),
 (2845, 3051),
 (3355, 3252),
 (3096, 2986),
 (3213, 3026),
 (2757, 3414),
 (3186, 2724),
 (2809, 3388),
 (3018, 3136),
 (3226, 2698),
 (3003, 171),
 (2783, 2932),
 (2864, 3362),
 (2825, 3075),
 (3339, 3324),
 (2782, 2969),
 (2989, 3249),
 (2669, 2679),
 (3100, 3002),
 (3337, 3107),
 (2665, 2675),
 (3241, 3412),
 (2762, 3275),
 (3377, 3261),
 (3052, 2873),
 (3172, 3118),
 (2853, 3070),
 (3433, 2924),
 (3262, 3179),
 (3119, 2906),
 (3299, 2849),
 (2661, 3391),
 (3035, 2833),
 (2763, 2974),
 (3221, 3214),
 (2990, 3412),
 (2833, 3298),
 (2956, 2946),
 (2707, 2778),
 (3279, 3263),
 (3339, 3284),
 (3051, 3201),
 (2716, 2720),
 (2676, 3232),
 (2820, 2697),
 (3201, 3261),
 (2742, 2894),
 (2797, 2937),
 (2905, 3108),
 (2909, 3090),
 (3303, 2978),
 (3070, 2863),
 (2669, 2683),
 (2988, 2777),
 (3116, 3152),
 (2906, 2880),
 (3299, 3203),
 (2735, 2976),
 (2909, 3250),
 (3201, 2796),
 (3431, 3329),
 (3129, 3226),
 (3201, 2720),
 (3170, 2937),
 (1405, 3406),
 (3368, 2997),
 (3226, 2839),
 (2993, 2987),
 (3089, 2716),
 (3191, 3359),
 (3077, 3103),
 (2978, 3010),
 (3330, 3038),
 (3026, 3022),
 (2825, 1758),
 (3387, 2683),
 (3235, 2863),
 (2944, 2815),
 (3295, 3412),
 (2689, 3022),
 (107, 1505),
 (3146, 3201),
 (3435, 3243),
 (3023, 3184),
 (2909, 2698),
 (3000, 3387),
 (2738, 2929),
 (2662, 2716),
 (3059, 3300),
 (3200, 3122),
 (2661, 3360),
 (3212, 3406),
 (2956, 2929),
 (3051, 3160),
 (2950, 2712),
 (2839, 3174),
 (3111, 3005),
 (3240, 3276),
 (1405, 3304),
 (2994, 2873),
 (3119, 3073),
 (2689, 3232),
 (2758, 3087),
 (3085, 2867),
 (3264, 2718),
 (3022, 3142),
 (3299, 3188),
 (2738, 2862),
 (3387, 3040),
 (2989, 2742),
 (3147, 2774),
 (3258, 3076),
 (2844, 2791),
 (2925, 3399),
 (2706, 3417),
 (2849, 2796),
 (3335, 3297),
 (3262, 3079),
 (3186, 3320),
 (3296, 3247),
 (3083, 2983),
 (2906, 2872),
 (2910, 2689),
 (3381, 3146),
 (2777, 2966),
 (3207, 2711),
 (3212, 3013),
 (3404, 3087),
 (2757, 3090),
 (3319, 2849),
 (2801, 3255),
 (2872, 2911),
 (2929, 2756),
 (2948, 3324),
 (3051, 3017),
 (3288, 2901),
 (3257, 2931),
 (3275, 3203),
 (3212, 2849),
 (2861, 3354),
 (2949, 2997),
 (2912, 3026),
 ...]

In [62]:
# Create an empty graph
G = nx.Graph()

# Add the edges from the edge list to the graph
G.add_edges_from(edges)

In [63]:
new_matrix=nx.adjacency_matrix(G)

In [64]:
Graph=new_matrix.toarray()

In [65]:
Graph.shape

(786, 786)

In [66]:
Graph

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)